# Generated by Django 5.0.1 on 2024-02-07 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendary', '0002_alter_cumpleanio_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cumpleanio',
            options={'verbose_name': 'Cumpleaño', 'verbose_name_plural': 'Cumpleaños'},
        ),
        migrations.AlterModelOptions(
            name='saludo',
            options={'verbose_name_plural': 'Saludos'},
        ),
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.AddField(
            model_name='saludo',
            name='fechaSaludo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha de Saludo'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fechaFin',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
