# Generated by Django 5.0.1 on 2024-02-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendary', '0005_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
    ]
