# Generated by Django 5.0.1 on 2024-02-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendary', '0006_remove_contacto_avisos_remove_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saludo',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
