# Generated by Django 5.0.1 on 2024-02-08 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendary', '0007_alter_saludo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
