# Generated by Django 5.0.1 on 2024-02-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendary', '0008_contacto_fecha_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
