# Generated by Django 5.0.1 on 2024-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
