# Generated by Django 5.0.1 on 2024-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cumpleanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dia', models.IntegerField()),
                ('mes', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Cumpleaño',
                'verbose_name_plural': 'Cumpleaños',
            },
        ),
    ]
