# Generated by Django 5.0.1 on 2024-02-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumpleanios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumpleanio',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
    ]
